name: Build and Deploy Changed Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: package-a changed since the main branch?
        id: changedAction
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: "@micro-site"
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead)

      # Do something more meaningful here, like do heavy computing, add PR label, etc.
      - name: Validate Action Output
        if: steps.changedAction.outputs.changed == 'true' # Check output if it changed or not (returns a boolean)
        run: echo 'micro-site changed! ${{ needs.build.outputs.affectedWorkspaces }}'

  # You'll want to delete this job if you don't plan to use the returned workspace names in a matrix job.
  build-affected:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        workspace: ${{ needs.build.outputs.affectedWorkspaces }}
    steps:
      - name: Dummy Build Step
        run: "echo 'Matrix run: ${{ matrix.workspace }} changed!'"