name: Build and Deploy Changed Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: 'Install npm packages'
        run: npm ci --quiet --legacy-peer-deps
        timeout-minutes: 5

      - name: "package-a changed in last commit?"
        id: changedAction
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: microsites
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead in the form of origin/<branchName>)