name: Check and Publish Changesets

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      publishedPackages: ${{ steps.set-packages.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "[ci] release"
          title: "[ci] release"
          publish: npm run publish
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Output for Published Packages
        id: set-packages
        run: |
          if [ "${{ steps.changesets.outputs.published }}" == "true" ]; then          
            names=$(echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '[.[] | .name] | @json')          
            echo "publishedPackages=${names}" >> $GITHUB_OUTPUT                 
          else
            echo "publishedPackages=[]" >> $GITHUB_OUTPUT            
          fi

  deploy:
    if: ${{ needs.release.outputs.publishedPackages != '[]' }}
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.publishedPackages) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build microsite
        run: npx turbo build --filter="${{ matrix.package }}..."

      - name: Deploy microsite
        run: npm run deploy-single-microsite -- ${{ matrix.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
