name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "[ci] release"
          title: "[ci] release"
          publish: npm run publish
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Output for Published Packages
        id: set-packages
        run: |
          if [ "${{ steps.changesets.outputs.published }}" == "true" ]; then
            echo "packages=${{ steps.changesets.outputs.publishedPackages }}" >> $GITHUB_OUTPUT            
          else
            echo "packages=[]" >> $GITHUB_OUTPUT            
          fi

  deploy:
    if: ${{ needs.release.outputs.packages != '[]' }}
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.packages) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Deploy microsite
        run: npm run deploy -- ${{ matrix.package.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
